### ISSUE TITLE
Does anyone know how to get past snockets being deprecated?

### ISSUE THREAD

**Issue by sapg** [gigablah/generator-dashing-go#4]
This is what I get when doing `yo dashing-go`.

git fetch -a origin (git://github.com/umurgdk/grunt-snockets) error: cannot open FETCH_HEAD: Permission denied
npm ERR! Error: No compatible version found: grunt-snockets@'umurgdk/grunt-snockets'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/share/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

Over at https://github.com/umurgdk/grunt-snockets  I see this message - 

"This project is no longer continoued. I don't use snockets anymore and highly recommend to use require.js instead! I no longer see any necassary to use a tool like snockets, sorry :)"

Thanks.

**Comment by gigablah** [comment]
That deprecation message shouldn't matter, since you're fetching directly from the github repository itself.

The error seems to be here:

```
git fetch -a origin (git://github.com/umurgdk/grunt-snockets) error: cannot open FETCH_HEAD: Permission denied
```

It could potentially be a UNIX permission issue... try running `chown -R` to give yourself ownership of everything under `node_modules`.

http://stackoverflow.com/questions/13195814/trying-to-git-pull-with-error-cannot-open-git-fetch-head-permission-denied

**Comment by sapg** [comment]
I deleted everything and started again, I still that that error.  I tried chown'ing even though I was already the owner.

If I ignore the error and go ahead and run `go run server.go` I see a white page with this message - 

"Try this: curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Hey, Look what I can do!" }' http://server:3000/widgets/welcome"

I'll keep plugging away until I find a solution.

**Comment by sapg** [comment]
OK, I fixed the git permissions error by `chown -R username ~/.npm.  But I still get this error -

npm ERR! Error: No compatible version found: grunt-snockets@'umurgdk/grunt-snockets'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/share/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/tv/my-dashboard
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.12
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tv/my-dashboard/npm-debug.log
npm ERR! not ok code 0

**Comment by sapg** [comment]
OK, I've fixed it, I had to give permissions back to my users on two more directories -

sudo chown -R username ~/tmp
sudo chown-R username ~/.tmp_versions

I also edited package.json and changed the grunt-snockets line to this - 

 "grunt-snockets": ">=0"

The sample dashboard loads up and works now.  On with creating my own. :-)
